{application,buffalo,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{buffalo_app,[]}},
              {env,[]},
              {modules,[buffalo,buffalo_app,buffalo_queuer,buffalo_sup,
                        buffalo_worker_sup]}]}.
